eureka.client:
  service-url:
      defaultZone: http://localhost:8761/eureka
spring.application.name: api-gateway
spring.cloud.gateway:
  routes[0]:
    id: character-maker-service
    uri: http://character-maker
    predicates[0]: Path=/api/maker
  routes[1]:
    id: characters-service
    uri: http://characters-service
    predicates[0]: Path=/api/characters