eureka.client:
  service-url:
    defaultZone: http://localhost:8761/eureka
spring.application.name: api-gateway
spring.cloud.gateway:
  routes[0]:
    id: character-maker-service
    uri: lb://character-maker-service
    predicates: Path=/api/maker
  routes[1]:
    id: characters-service
    uri: lb://characters-service
    predicates: Path=/api/characters
  routes[2]:
    id: characters-service
    uri: lb://characters-service
    predicates: Path=/api/characters/random
  routes[3]:
    id: characters-service
    uri: lb://characters-service
    predicates: Path=/api/characters/character/{id}
