spring:
  application.name: characters-service
  datasource:
    url: jdbc:postgresql://localhost:5432/characters
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
eureka:
  client.serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server.port: 0